-- PumpFun Auto Trader AI Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists users (
    id bigint generated by default as identity primary key,
    telegram_id text unique not null,
    alerts_enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists x_sources (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    name text not null,
    rss_url text not null,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists idx_x_sources_user_active
on x_sources (telegram_id, active);

create table if not exists seen_source_items (
    id bigint generated by default as identity primary key,
    source_id bigint not null,
    item_id text not null,
    created_at timestamptz not null default now(),
    unique (source_id, item_id)
);

create index if not exists idx_seen_source_items
on seen_source_items (source_id, item_id);

create table if not exists detected_tokens (
    id bigint generated by default as identity primary key,
    mint text unique not null,
    source text not null,
    payload jsonb,
    created_at timestamptz not null default now()
);

create table if not exists sent_alerts (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    mint text not null,
    alert_type text not null,
    payload jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_sent_alerts_recent
on sent_alerts (telegram_id, created_at desc);

create table if not exists trades (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    mint text not null,
    mode text not null,
    status text not null default 'open',
    amount_sol numeric not null,
    entry_price_usd numeric,
    highest_price_usd numeric,
    exit_price_usd numeric,
    buy_signature text,
    buy_response jsonb,
    sell_response jsonb,
    ai_score integer,
    source_type text,
    close_note text,
    expires_at timestamptz,
    closed_at timestamptz,
    raw jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_trades_user_status
on trades (telegram_id, status);

create index if not exists idx_trades_mint
on trades (telegram_id, mint);

create index if not exists idx_trades_created
on trades (telegram_id, created_at desc);
